env:
  node: true
  jest/globals: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
rules:
  no-console:
    - warn
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  jest/no-disabled-tests:
    - warn
  jest/no-focused-tests:
    - error
  jest/no-identical-title:
    - error
  jest/valid-expect:
    - error
plugins:
  - jest